version: "3.0"
services:
  gzctf:
    image: gztime/gzctf:latest
    restart: always
    environment:
      - "LC_ALL=en_US.UTF-8"
    ports:
      - "8080:8080"
    volumes:
      - "gzctf-files:/app/files"
      - "./appsettings.json:/app/appsettings.json:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    depends_on:
      - db
      - cache
  gzctf-bot:
    build: bot
    restart: always
    environment:
      GZCTF_DISCORD_WEBHOOK: "{{.DiscordWebhook}}"
      POSTGRES_PASSWORD: postgres
  db:
    image: postgres:alpine
    restart: always
    environment:
      - "POSTGRES_PASSWORD=postgres"
    volumes:
      - "postgres-data:/var/lib/postgresql/data"

  cache:
    image: redis:alpine
    restart: always

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - gzctf
    volumes:
      - ./nginx/ssl.conf:/etc/nginx/sites-available/{{.PublicEntry}}
      - ./letsencrypt:/etc/letsencrypt
    ports:
      - "443:443"
      - "80:80"

volumes:
  gzctf-files:
  postgres-data: