version: "3"

services:
  proxy:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./html/:/var/www/html/:ro
    ports:
      - 80:80
    networks:
      - internal

  app:
    build: ./
    networks:
      - internal

networks:
  internal:
