version: '3'

services:
  app:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html:ro
      - ./proxy.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - internal
    depends_on:
      - bot
  bot:
    build: bot
    environment:
      APPNAME: Admin
      APPURL: http://app/
      APPURLREGEX: ^http://app/.*$
      APPFLAG: dev{flag}
      APPLIMIT: 2
      APPLIMITTIME: 60
      USE_PROXY: 1
    networks:
      - internal

networks:
  internal:
