services:
  example:
    build: .
    restart: on-failure
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      # openssl s_client -connect localhost:80 -servername static-attachment.category.{{.PublicEntry}} -quiet
      - "traefik.tcp.routers.service.rule=HostSNI(`static-attachment.category.{{.PublicEntry}}`)"
      - "traefik.tcp.routers.service.tls=true"
      - "traefik.tcp.services.service.loadbalancer.server.port=8011"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "256M"
        reservations:
          cpus: "0.25"
          memory: "128M"

networks:
  traefik:
    external: true